list:
	go run main.go search tesujiro TheGoprogrammingLanguage

create:
	go run main.go create tesujiro TheGoprogrammingLanguage

read:
	go run main.go read tesujiro TheGoprogrammingLanguage 1

update:
	go run main.go update tesujiro TheGoprogrammingLanguage 1

close:
	go run main.go close tesujiro TheGoprogrammingLanguage 30
