list:
	go run main.go search tesujiro ProgrammingLanguageGo

create:
	go run main.go create tesujiro ProgrammingLanguageGo

read:
	go run main.go read tesujiro ProgrammingLanguageGo 1

update:
	go run main.go update tesujiro ProgrammingLanguageGo 1

close:
	go run main.go close tesujiro ProgrammingLanguageGo 30
